### ISSUE TITLE
Start SEGA game IDs

### ISSUE THREAD

**Issue by Poliwrath** [Shizmob/arcade-docs#10]
The ``S[B,D]XX`` things.

The third/fourth character follows a year scheme similar to konami's (third might be release year, fourth might be random, I guessed it might've been month but they also use X/Z in some games). They've been in use at least since lindbergh (though they're only visible on ring* and newer keychips afaik).

I know this will especially be useful for people on various forums, I've seen plenty of "what game is this" threads because people often buy ring* boards and have no idea what the game is.

**Comment by Shizmob** [comment]
Yep, this would be very useful. I have a pretty sizable database of game IDs I've been meaning to merge in, just need a way to untangle them from my notes format which also includes install media and keychip ID where known.

I don't think the third and fourth character are a year scheme, but rather that they just roll over (example: Initial D8 JP is SBZZ, the first game I have after that is SDAX.

**Comment by Shizmob** [comment]
The last character also seems more evenly distributed than it would be if it was a month code:

```
$ grep -Eo 'S[BD][A-Z]{2}' models.txt | cut -c4 | sort | uniq -c
  11 A
   7 B
   6 C
   8 D
   7 E
  18 F
  10 G
   8 H
   8 J
   5 K
   4 L
  19 M
  10 N
   8 P
  12 Q
  10 R
   8 S
  13 T
   9 U
   9 V
   4 W
   9 X
   9 Y
   8 Z
   ```

**Comment by Poliwrath** [comment]
Yeah, I was HOPING it was month (I was using SDHF as reference, which soooorta fits) until I remembered ID8 exists >_>
For the third character it's definitely incremented by year at least. Notice how there's no games past SDH so far, and SDHB/SDHF have been introduced this year.

**Comment by Shizmob** [comment]
Just going through my game list, I don't think this fully makes sense yet.

The earliest game I have with an S-code is StarHorse2: New Generation, which is SBKM. Assuming SDH* is this year, and we rolled over from SBZ to SDA, that'd mean it was `ord('Z')-ord('K')+1` years from `SBK` to `SDA`, and `ord('H')-ord('A')` years from `SDA` until now. That'd add up to 23 years. StarHorse2 was released in 2005: 16 years ago.

What could potentially happen is that they reset to the next character at the start of a year and if they release more than 26 games halfway, just roll over. However, I'm not sure the data supports this: for the SDG and SDH example, I see late-SDG codes in my notes (like SDGW) that indicate they just rolled over.

**Comment by Poliwrath** [comment]
It might just be a coincidence then :'(
Guilty Gear Strive released on PC and arcades 2021, that has game code SDGM...

**Comment by Shizmob** [comment]
It was worth a shot checking! I'll see if I can wrangle my notes into an acceptable format. The main problem is linking between game IDs, install media and platform...

**Comment by Poliwrath** [comment]
The only ones I have available are:
MDA-U0048C - Edel Sand Plus (SDBN, 1.10.03, NuSX AAW)
MDA-U0070 - maimai milk 1.90 / RE2?

I guess Naomi/Chihiro/Lindbergh can mostly be sourced from mame/ebay, iirc there's a couple of random game revisions on ebay that aren't documented anywhere.

**Comment by Shizmob** [comment]
Just did an initial push of mostly my raw notes, should be a decent start, at least. Going through them all reminds me I spend too much time on this stuff...
