### ISSUE TITLE
More system 573 products and identifiers from MAME

### ISSUE THREAD

**Issue by voidderef** [Shizmob/arcade-docs#4]
* See comments at the top: https://github.com/mamedev/mame/blob/master/src/mame/drivers/ksys573.cpp
* See game list at the bottom regarding known versions: https://github.com/mamedev/mame/blob/master/src/mame/drivers/ksys573.cpp#L5952

**Comment by Shizmob** [comment]
As far as I know, at least the hardware stuff from MAME is already covered by the existing 573 documentation. The games would definitely need adding, though.

**Comment by voidderef** [comment]
Yes, this is purely about extending the game and products list and not about documenting the actual hardware in detail. I was rather unspecific about that in the description.

**Comment by 987123879113** [comment]
The comments at the top of ksys573.cpp are very out of date. I wouldn't recommend using that as a reference if you can help it. The games list at the bottom is much more accurate.

**Comment by voidderef** [comment]
> The comments at the top of ksys573.cpp are very out of date. I wouldn't recommend using that as a reference if you can help it. The games list at the bottom is much more accurate.

I guess that's a fair comment to say that it doesn't hurt to cross-check the top and bottom of the file with the knowledge we have about various product codes and formats so far. Thanks for pointing that out.

**Comment by Shizmob** [comment]
Thanks for the notice, in https://github.com/Shizmob/arcade-docs/commit/3cb49b9bbe6eecaac18a92737c58c51932ef0a93 I used the bottom list as a reference. This is done now, so closing the issue.
