### ISSUE TITLE
Addition to: arcade-docs/blob/main/konami/boards.md#76

### ISSUE THREAD

**Issue by mnm-isola** [shizmob/arcade-docs#69]
76
MBD: Ennoconn ADE-704B
STH: Intel HM76
CPU: Intel Celeron 1020E
**_RAM: 1x Innodisk SODIMM DDR3L 2GB_**
GPU: AMD Radeon E6760
HDD: WDC WD3200LPCX (320GB) [KFC] SSD: ? [KFC] (SEA mini cab) **_SSD: Intel SSD 320 Series 80GB (Region unknown, possibly Uniana made cab sold to HK) [KFC]_**
SND: Realtek ALC888 Series
IO: [KFC/PAN] [KFCA](https://github.com/shizmob/arcade-docs/blob/main/konami/io.md#kfca)
OS: Windows XP Embedded (SP2) [KFC], Windows Embedded 7 Standard (SP1) [KFC] (SEA mini cab) [NCG] [OSP] Games: KFC, NCG, PAN, OSP, PTL
BIOS: AMIBIOS
Ref: https://twitter.com/ham56p/status/1115528175142850561, https://page.auctions.yahoo.co.jp/jp/auction/o1010920842
![20240124_162310](https://github.com/shizmob/arcade-docs/assets/35838921/9abe905d-4cd1-42ef-beb3-2c2818191d4f)
![20240124_164118](https://github.com/shizmob/arcade-docs/assets/35838921/8d62a5ed-2250-4215-92d1-11885a6ae886)
![20240124_164701](https://github.com/shizmob/arcade-docs/assets/35838921/c73c45d9-8326-4339-a2f9-0567b4ba03fb)
![20240124_162017](https://github.com/shizmob/arcade-docs/assets/35838921/4a6d7a73-0f5f-4f38-9193-1215b433d35e)
![20240124_162025](https://github.com/shizmob/arcade-docs/assets/35838921/b109f161-f001-4909-9ccc-4494f36d218b)

**Comment by mnm-isola** [comment]
![20240124_161956](https://github.com/shizmob/arcade-docs/assets/35838921/c112d300-77c9-44cc-8b83-5c8dce3fb92e)

**Comment by Randname666** [comment]
Done in commit d3077ee.
