### ISSUE TITLE
Andamiro's official hardware names

### ISSUE THREAD

**Issue by soundsnow** [shizmob/arcade-docs#70]
*Changed company name from 'Oksan Electronics' (1992) to 'Andamiro' (1998)
*In-house technology development 2D Board MIDAS and 3D Board SPACE development completed (1998)
*Launch dance simulation game Pump It Up (1998)
https://www.andamiro.com/global/sub4/4_2.php

MIDAS: Reengineered NeoGeo, SPACE: PC
You called SPACE MK1?
I don't think Andamiro likes MK1

**Comment by Randname666** [comment]
Merged with #71 .
