### ISSUE TITLE
Namco Bandai ES2+ missing game: 海物語?

### ISSUE THREAD

**Issue by soundsnow** [shizmob/arcade-docs#77]
I don’t know which game it is because 海物語 is a series
I found it on this website
https://aucview.aucfan.com/yahoo/e1044281068/#rm&tg=detailtextModal
☆(F0324-1)NAMCO BANDAI System ES2+ SYS ES2P (A) ASSY 海物語 メダルゲーム 基板

**Comment by Randname666** [comment]
You mean [海物語ラッキーマリンツアーズ](https://bandainamco-am.co.jp/am/mg/lmtours/) ? As that seems to be the only game in the series handled by Namco.

海物語 seems to be an IP owned by Sanyo Bussan (Not Sanyo Electronic which many people are more familar with) and 海物語 series pachinkos manufactured by Sanyo Bussan use an almost completely proprietary board and doesn't look like PC based. Something like [this](https://static.mercdn.net/item/detail/orig/photos/m84438316747_5.jpg?1701549668).

**Comment by Randname666** [comment]
Added in commit afe710e.
